<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="5" passed="1" failed="4" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-01-27T20:41:08 IST" name="Default suite" finished-at="2023-01-27T20:41:34 IST" duration-ms="26162">
    <groups>
    </groups>
    <test started-at="2023-01-27T20:41:08 IST" name="Default test" finished-at="2023-01-27T20:41:34 IST" duration-ms="26162">
      <class name="PlanetSuperHerossStoreTest.PlanetsSuperHerosStoreTest">
        <test-method is-config="true" signature="openBroswer()[pri:0, instance:PlanetSuperHerossStoreTest.PlanetsSuperHerosStoreTest@783a467b]" started-at="2023-01-27T20:41:08 IST" name="openBroswer" finished-at="2023-01-27T20:41:17 IST" duration-ms="9622" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openBroswer -->
        <test-method signature="VerifyPinAndCity()[pri:0, instance:PlanetSuperHerossStoreTest.PlanetsSuperHerosStoreTest@783a467b]" started-at="2023-01-27T20:41:17 IST" name="VerifyPinAndCity" finished-at="2023-01-27T20:41:23 IST" duration-ms="5658" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [Mumbai] but found [No stores available in your area]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [Mumbai] but found [No stores available in your area]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at PlanetSuperHerossStoreTest.PlanetsSuperHerosStoreTest.VerifyPinAndCity(PlanetsSuperHerosStoreTest.java:99)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- VerifyPinAndCity -->
        <test-method is-config="true" signature="failedtestCasesSS(org.testng.ITestResult)[pri:0, instance:PlanetSuperHerossStoreTest.PlanetsSuperHerosStoreTest@783a467b]" started-at="2023-01-27T20:41:23 IST" name="failedtestCasesSS" finished-at="2023-01-27T20:41:23 IST" duration-ms="225" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=VerifyPinAndCity status=FAILURE method=PlanetsSuperHerosStoreTest.VerifyPinAndCity()[pri:0, instance:PlanetSuperHerossStoreTest.PlanetsSuperHerosStoreTest@783a467b] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failedtestCasesSS -->
        <test-method signature="verifyPinAndCity(java.lang.String)[pri:0, instance:PlanetSuperHerossStoreTest.PlanetsSuperHerosStoreTest@783a467b]" started-at="2023-01-27T20:41:24 IST" name="verifyPinAndCity" data-provider="input" finished-at="2023-01-27T20:41:27 IST" duration-ms="3191" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[400093]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [Mumbai] but found [No stores available in your area],
expected [Mumbai] but found [No stores available in your area]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [Mumbai] but found [No stores available in your area],
expected [Mumbai] but found [No stores available in your area]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at PlanetSuperHerossStoreTest.PlanetsSuperHerosStoreTest.verifyPinAndCity(PlanetsSuperHerosStoreTest.java:69)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyPinAndCity -->
        <test-method is-config="true" signature="failedtestCasesSS(org.testng.ITestResult)[pri:0, instance:PlanetSuperHerossStoreTest.PlanetsSuperHerosStoreTest@783a467b]" started-at="2023-01-27T20:41:27 IST" name="failedtestCasesSS" finished-at="2023-01-27T20:41:27 IST" duration-ms="258" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=verifyPinAndCity status=FAILURE method=PlanetsSuperHerosStoreTest.verifyPinAndCity(java.lang.String)[pri:0, instance:PlanetSuperHerossStoreTest.PlanetsSuperHerosStoreTest@783a467b] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failedtestCasesSS -->
        <test-method signature="verifyPinAndCity(java.lang.String)[pri:0, instance:PlanetSuperHerossStoreTest.PlanetsSuperHerosStoreTest@783a467b]" started-at="2023-01-27T20:41:27 IST" name="verifyPinAndCity" data-provider="input" finished-at="2023-01-27T20:41:30 IST" duration-ms="2415" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[400064]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [Mumbai] but found [No stores available in your area],
expected [Mumbai] but found [No stores available in your area],
expected [Mumbai] but found [No stores available in your area]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [Mumbai] but found [No stores available in your area],
expected [Mumbai] but found [No stores available in your area],
expected [Mumbai] but found [No stores available in your area]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at PlanetSuperHerossStoreTest.PlanetsSuperHerosStoreTest.verifyPinAndCity(PlanetsSuperHerosStoreTest.java:69)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyPinAndCity -->
        <test-method is-config="true" signature="failedtestCasesSS(org.testng.ITestResult)[pri:0, instance:PlanetSuperHerossStoreTest.PlanetsSuperHerosStoreTest@783a467b]" started-at="2023-01-27T20:41:30 IST" name="failedtestCasesSS" finished-at="2023-01-27T20:41:30 IST" duration-ms="362" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=verifyPinAndCity status=FAILURE method=PlanetsSuperHerosStoreTest.verifyPinAndCity(java.lang.String)[pri:0, instance:PlanetSuperHerossStoreTest.PlanetsSuperHerosStoreTest@783a467b] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failedtestCasesSS -->
        <test-method signature="verifyPinAndCity(java.lang.String)[pri:0, instance:PlanetSuperHerossStoreTest.PlanetsSuperHerosStoreTest@783a467b]" started-at="2023-01-27T20:41:30 IST" name="verifyPinAndCity" data-provider="input" finished-at="2023-01-27T20:41:31 IST" duration-ms="1266" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[Mumbai]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [Mumbai] but found [No stores available in your area],
expected [Mumbai] but found [No stores available in your area],
expected [Mumbai] but found [No stores available in your area],
expected [Mumbai] but found [No stores available in your area]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [Mumbai] but found [No stores available in your area],
expected [Mumbai] but found [No stores available in your area],
expected [Mumbai] but found [No stores available in your area],
expected [Mumbai] but found [No stores available in your area]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at PlanetSuperHerossStoreTest.PlanetsSuperHerosStoreTest.verifyPinAndCity(PlanetsSuperHerosStoreTest.java:69)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyPinAndCity -->
        <test-method is-config="true" signature="failedtestCasesSS(org.testng.ITestResult)[pri:0, instance:PlanetSuperHerossStoreTest.PlanetsSuperHerosStoreTest@783a467b]" started-at="2023-01-27T20:41:31 IST" name="failedtestCasesSS" finished-at="2023-01-27T20:41:32 IST" duration-ms="350" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=verifyPinAndCity status=FAILURE method=PlanetsSuperHerosStoreTest.verifyPinAndCity(java.lang.String)[pri:0, instance:PlanetSuperHerossStoreTest.PlanetsSuperHerosStoreTest@783a467b] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failedtestCasesSS -->
        <test-method signature="verifyTitleFindStore()[pri:0, instance:PlanetSuperHerossStoreTest.PlanetsSuperHerosStoreTest@783a467b]" started-at="2023-01-27T20:41:32 IST" name="verifyTitleFindStore" finished-at="2023-01-27T20:41:33 IST" duration-ms="1466" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyTitleFindStore -->
        <test-method is-config="true" signature="failedtestCasesSS(org.testng.ITestResult)[pri:0, instance:PlanetSuperHerossStoreTest.PlanetsSuperHerosStoreTest@783a467b]" started-at="2023-01-27T20:41:33 IST" name="failedtestCasesSS" finished-at="2023-01-27T20:41:33 IST" duration-ms="0" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=verifyTitleFindStore status=SUCCESS method=PlanetsSuperHerosStoreTest.verifyTitleFindStore()[pri:0, instance:PlanetSuperHerossStoreTest.PlanetsSuperHerosStoreTest@783a467b] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failedtestCasesSS -->
        <test-method is-config="true" signature="closeBroswer()[pri:0, instance:PlanetSuperHerossStoreTest.PlanetsSuperHerosStoreTest@783a467b]" started-at="2023-01-27T20:41:33 IST" name="closeBroswer" finished-at="2023-01-27T20:41:34 IST" duration-ms="758" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBroswer -->
      </class> <!-- PlanetSuperHerossStoreTest.PlanetsSuperHerosStoreTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
